# $ \color{blue}{\text{EJERCICIO 1}} $

## $ \color{blue}{\text{Idem ejercicio 2b de la Guía 1, pero aplicando transformada Z}} $

![title](Resources/EJ2/ej2B.png)

<br>

Se llama $w(n)$ a la señal en el nodo marcado con rojo en la figura anterior, de forma que se tienen las siguientes señales:

$$ x(nT)$$
$$ w(nT) = x(nT) + w((n-1)T) - 0,5 \cdot w((n-2)T)$$
$$ y(nT) = w(nT) + w((n-1)T)$$

<br>

Aplicando la transformada $Z$ a las ecuaciones anteriores, se obtienen:

$$ X(z) $$
$$ W(z) = X(z) + W(z) \cdot z^{-1} - 0,5 \cdot W(z) \cdot z^{-2}$$
$$ Y(z) = W(z) + W(z) \cdot z^{-1} $$

De las ecuaciones anteriores se obtiene:
<br>
$Y(z) = X(z) \cdot \frac{1+z^{-1}}{1-z^{-1}+0,5z^{-2}}$
<br>
$\implies Y(z) \cdot (1-z^{-1}+0,5z^{-2}) = X(z) \cdot (1 + z^{-1})$
<br>
$\implies Y(z) = X(z) + X(z) \cdot z^{-1} + Y(z) \cdot z^{-1} - 0,5 Y(z) z^{-2}$

<br>
<br>

Y finalmente, antitransformando la última expresión usando la transformada inversa de $Z$, se obtiene:

$$y(nT) = x(nT) + x((n-1)T) + y((n-1)T) - 0,5 \cdot y((n-2)T)$$ 

En la $Guía 1$ se resolvió este sistema pero sin aplicar transformada $Z$, y tanto de esa forma como de esta, se llegó al mismo resultado. Aplicar la transformada $Z$ permitió obtenerlo de manera más rapida y más sensilla, evitando una mayor camtidad de cuentas y pasos como lo fue sin transformada $Z$.



# $ \color{blue}{\text{EJERCICIO 1}} $

## $ \color{blue}{\text{Idem ejercicio 9 de la Guía 1, pero aplicando transformada Z}} $

$$ y(nT) = 0.5\cdot x((n-2)T) + \alpha y((n-1)T) + \beta y((n-2)T) $$

$$ Y(z) = 0.5*X(z) \cdot z^{-2} + \alpha Y(z)\cdot z^{-1} + \beta Y(z) \cdot z^{-2}  $$

$$ H(z) = \frac{ 0.5 \cdot z^{-2}}{1-\alpha \cdot z^{-1} -\beta  \cdot z^{-2} } $$

$$ H(z) = \frac{ 0.5}{z^{2}-\alpha \cdot z^{1} -\beta   } $$


### $ \color{red}{\text{Caso A}} $

$$ \alpha = 1 $$
$$ \beta = -1/2 $$

Tras aplicar fracciones simples:

$$ H(z) = -0.5 \cdot i \cdot (\frac{1}{z-0.5-0.5i} - \frac{1}{z-0.5+0.5i}) $$

Antitransformando se obtiene la respuesta impulsiva:

$$ h(n) = -0.5 \cdot i \cdot ((0.5+0.5 \cdot i)^ {n-1} \cdot u(n-1) - (0.5-0.5 \cdot i)^{n-1} \cdot u(n-1) )  $$

Para hallar la respuesta al escalón:

$$y(n) = u(n) * h(n)$$
$$y(n) = -0.5 \cdot i \cdot (\sum_{-\infty}^\infty u(k) \cdot (0.5+0.5\cdot i)^{n-k-1} \cdot u(n-k-1) + \sum_{-\infty}^\infty u(k) \cdot (0.5-0.5\cdot i)^{n-k-1} \cdot u(n-k-1)) $$

Simplificando:

$$y(n) = -0.5 \cdot i \cdot (\sum_{0}^{n-1}  (0.5+0.5\cdot i)^{n-k-1}  + \sum_{0}^{n-1}  (0.5-0.5\cdot i)^{n-k-1} ) $$



### $ \color{red}{\text{Caso B}} $

$$ \alpha = 1/2 $$
$$ \beta = -1/8 $$

Tras aplicar fracciones simples:

$$ H(z) = i \cdot (\frac{1}{z-(\frac{1}{4}-\frac{1}{4}i)} - \frac{1}{z-(\frac{1}{4}+\frac{1}{4}i)}) $$

Antitransformando se obtiene la respuesta impulsiva:

$$ h(n) = -i  \cdot ((\frac{1}{4}+\frac{1}{4}i)^ {n-1} \cdot u(n-1) - (\frac{1}{4}-\frac{1}{4}i)^{n-1} \cdot u(n-1) )  $$

Para hallar la respuesta al escalón:

$$y(n) = u(n) * h(n)$$

$$y(n) = -i \cdot (\sum_{0}^{n-1}  (\frac{1}{4}+\frac{1}{4}i)^{n-k-1}  + \sum_{0}^{n-1}  (\frac{1}{4}-\frac{1}{4}i)^{n-k-1} ) $$

### $ \color{red}{\text{Caso C}} $

$$ \alpha = 5/4 $$
$$ \beta = -25/32 $$

Tras aplicar fracciones simples:


$$ H(z) = \frac{2}{5} \cdot i \cdot (\frac{1}{z-(\frac{5}{8}-\frac{5}{8}i)} - \frac{1}{z-(\frac{5}{8}+\frac{5}{8}i)}) $$

Antitransformando se obtiene la respuesta impulsiva:

$$ h(n) = - \frac{2}{5} \cdot i  \cdot ((\frac{5}{8}+\frac{5}{8}i)^ {n-1} \cdot u(n-1) - (\frac{5}{8}-\frac{5}{8}i)^{n-1} \cdot u(n-1) )  $$

Para hallar la respuesta al escalón:

$$y(n) = u(n) * h(n)$$

$$y(n) = - \frac{2}{5} \cdot i \cdot (\sum_{0}^{n-1}  (\frac{5}{8}+\frac{5}{8}i)^{n-k-1}  + \sum_{0}^{n-1}  (\frac{5}{8}-\frac{5}{8}i)^{n-k-1} ) $$

# $ \color{blue}{\text{EJERCICIO 3}} $

## $ \color{blue}{\text{Ítem a}} $
A partir de la siguiente función transferencia, se hará uso del criterio Jury-Marden para determinar si el sistema que representa es estable:
$$ H(z) = \frac{z^6}{ 6 \cdot z^6 + 5 \cdot z^5 + 4 \cdot z^4 + 3 \cdot z^3 + 2 \cdot z^2 + z + 1 } $$

Se toma el polinomio:
$$ f(z) = 6 \cdot z^6 + 5 \cdot z^5 + 4 \cdot z^4 + 3 \cdot z^3 + 2 \cdot z^2 + z + 1 $$
Se lo normaliza y se lo iguala a 0:
$$ f_n(z) = z^6 + \frac{5}{6} \cdot z^5 + \frac{4}{6} \cdot z^4 + \frac{3}{6} \cdot z^3 + \frac{2}{6} \cdot z^2 + \frac{1}{6} z + \frac{1}{6} = 0 $$

Se evalúan las condiciones necesarias para un polinomio de orden par, observando que:
$$ \text{(i)} \quad f_n(1) = \frac{11}{3} > 0 $$
$$ \text{(ii)} \quad f_n(-1) = \frac{2}{3} > 0 $$
$$ \text{(iii)} \quad \left| a_0 \right| < 1 $$

Es decir, el polinomio normalizado evaluado en 1 y -1 es mayor a 0, y el coeficiente normalizado de menor orden, es menor en módulo a 1.

Se procede a evaluar las condiciones suficientes. Par ello se confroman las siguientes matrices cuadradas:

In [0]:
import numpy as np

In [0]:
M1 = np.matrix([
    [1, 5/6, 4/6, 3/6, 2/6, 1/6, 1/6],
    [0, 1, 5/6, 4/6, 3/6, 2/6, 1/6],
    [0, 0, 1, 5/6, 4/6, 3/6, 2/6],
    [0, 0, 0, 1, 5/6, 4/6, 3/6],
    [0, 0, 0, 0, 1, 5/6, 4/6],
    [0, 0, 0, 0, 0, 1, 5/6],
    [0, 0, 0, 0, 0, 0, 1]
])
M2 = np.matrix([
    [1, 5/6, 4/6, 3/6, 2/6, 1/6, 1/6],
    [5/6, 4/6, 3/6, 2/6, 1/6, 1/6, 0],
    [4/6, 3/6, 2/6, 1/6, 1/6, 0, 0],
    [3/6, 2/6, 1/6, 1/6, 0, 0, 0],
    [2/6, 1/6, 1/6, 0, 0, 0, 0],
    [1/6, 1/6, 0, 0, 0, 0, 0],
    [1/6, 0, 0, 0, 0, 0, 0]
])

H = M1 + M2

Y se comprueba que la suma de ellas tiene determinantes positivos de adentro hacia afuera:

In [26]:
H_size = int(np.ceil(np.size(H, 0)))
H_size_half = int(np.floor(H_size / 2))
for i in range(H_size_half+1):
  M = H[H_size_half-i:H_size_half+1+i, H_size_half-i:H_size_half+1+i]
  print('La matriz:')
  print('{}'.format(np.around(M, 3)))
  print('')
  print('Tiene un determinante de {:.3f}'.format(np.linalg.det(M)))
  print('')
  print('')

La matriz:
[[1.167]]

Tiene un determinante de 1.167


La matriz:
[[1.333 1.    0.833]
 [0.167 1.167 0.833]
 [0.167 0.    1.   ]]

Tiene un determinante de 1.366


La matriz:
[[1.667 1.333 1.    0.667 0.5  ]
 [0.5   1.333 1.    0.833 0.5  ]
 [0.333 0.167 1.167 0.833 0.667]
 [0.167 0.167 0.    1.    0.833]
 [0.167 0.    0.    0.    1.   ]]

Tiene un determinante de 1.592


La matriz:
[[2.    1.667 1.333 1.    0.667 0.333 0.333]
 [0.833 1.667 1.333 1.    0.667 0.5   0.167]
 [0.667 0.5   1.333 1.    0.833 0.5   0.333]
 [0.5   0.333 0.167 1.167 0.833 0.667 0.5  ]
 [0.333 0.167 0.167 0.    1.    0.833 0.667]
 [0.167 0.167 0.    0.    0.    1.    0.833]
 [0.167 0.    0.    0.    0.    0.    1.   ]]

Tiene un determinante de 1.813




Consecuentemente, queda determinado que el sistema es estable y todos sus polos se encuentran dentro de la circunferencia unitaria.

# $ \color{blue}{\text{EJERCICIO 6}} $
## $ \color{blue}{\text{Ítem a}} $

Dada una función de transferencia $ H $ de la forma:
$$ H(z) = \frac{b_m \cdot z^m + b_{m-1} \cdot z^{m-1} + ... + b_1 \cdot z + b_0}{a_n \cdot z^n + a_{n-1} \cdot z^{n-1} + ... + a_1 \cdot z + a_0} $$

Con:
$$ a_i \in {\rm I\!R} \quad \text{para todo} \quad i=0,1,...,n  $$
$$ b_j \in {\rm I\!R} \quad \text{para todo} \quad j=0,1,...,m  $$

$$ \left| H\left( e^{j\omega} \right) \right|^2 = H\left( e^{j\omega} \right) \cdot \overline{H\left( e^{j\omega} \right)} $$

Teniendo en cuenta que:
$$ \overline{H\left( z \right)} = \frac{\overline{b_m \cdot z^m + b_{m-1} \cdot z^{m-1} + ... + b_1 \cdot z + b_0}}{\overline{a_n \cdot z^n + a_{n-1} \cdot z^{n-1} + ... + a_1 \cdot z + a_0}} = \frac{b_m \cdot \overline{z}^m + b_{m-1} \cdot \overline{z}^{m-1} + ... + b_1 \cdot \overline{z} + b_0}{a_n \cdot \overline{z}^n + a_{n-1} \cdot \overline{z}^{n-1} + ... + a_1 \cdot \overline{z} + a_0} $$

Entonces:
$$ \overline{H\left( e^{j\omega} \right)} = H\left( e^{-j\omega} \right) $$

Por lo tanto:
$$  \left| H\left( e^{j\omega} \right) \right|^2 = \left. H\left( z \right) \cdot H\left( z^{-1} \right) \right\vert_{z = e^{j\omega}} $$

## $ \color{blue}{\text{Ítem b}} $

Dada la función transferencia:
$$ H(z) = \frac{1 - a \cdot z + b \cdot z^2}{b - a \cdot z + z^2} $$

La ganancia de la misma estará dada por:
$$  \left| H\left( e^{j\omega} \right) \right|^2 = \left. H\left( z \right) \cdot H\left( z^{-1} \right) \right\vert_{z = e^{j\omega}} = \frac{1 - a \cdot e^{j\omega} + b \cdot e^{2 \cdot j\omega}}{b - a \cdot e^{j\omega} + e^{2 \cdot j\omega}} \cdot \frac{1 - a \cdot e^{-j\omega} + b \cdot e^{-2 \cdot j\omega}}{b - a \cdot e^{-j\omega} + e^{-2 \cdot j\omega}} $$

Multiplicando numerador y denominador por $ e^{2 \cdot j\omega} $:
$$ \frac{1 - a \cdot e^{j\omega} + b \cdot e^{2 \cdot j\omega}}{b - a \cdot e^{j\omega} + e^{2 \cdot j\omega}} \cdot \frac{b - a \cdot e^{j\omega} + e^{2 \cdot j\omega}}{1 - a \cdot e^{j\omega} + b \cdot e^{2 \cdot j\omega}} = 1 $$

## $ \color{blue}{\text{Ítem c}} $

Escribiendo los polinomios del numerador y denominador en su forma factorial, se tiene que:
$$ H(z) = \frac{1 - a \cdot z + b \cdot z^2}{b - a \cdot z + z^2} = \frac{b \cdot \left( z - \frac{a + \sqrt{a^2 - 4 \cdot b}}{2 \cdot b} \right) \left( z - \frac{a - \sqrt{a^2 - 4 \cdot b}}{2 \cdot b} \right)}{\left( z - \frac{a + \sqrt{a^2 - 4 \cdot b}}{2} \right) \left( z - \frac{a - \sqrt{a^2 - 4 \cdot b}}{2} \right)} $$

Por inspección de la expresión anterior se puede observar que los polos y raíces se dan en pares conjugados.

Con el fin de comprobar la reciprocidad en los pares de polos y ceros se comprueban las siguientes igualdades.
En primer lugar:

$$  (\frac{a+ \sqrt{a^2-4b}}{2b}) \cdot (\frac{a- \sqrt{a^2-4b}}{2}) = 1   $$
$$  \frac{a^2 - a \cdot \sqrt{a^2-4b} + a \cdot  \sqrt{a^2-4b} - a^2 +4b }{4b} = 1  $$
$$ \frac{4b}{4b} = 1$$
$$ 1 = 1$$

Lo cual queda comprobado. Por otra parte:

$$  (\frac{a- \sqrt{a^2-4b}}{2b}) \cdot (\frac{a+ \sqrt{a^2-4b}}{2}) = 1   $$

$$  \frac{a^2 - a \cdot \sqrt{a^2-4b} + a \cdot  \sqrt{a^2-4b} - a^2 +4b }{4b} = 1  $$
$$ \frac{4b}{4b} = 1$$
$$ 1 = 1$$

Dado que ambas expresiones cumplen la igualdad a 1, se concluye que los pares son recíprocos. 

De esta forma, queda demostrado que los polos y ceros ocurren en pares recíprocos y conjugados.



